version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
        environment:
          BUNDLER_VERSION: 2.0.1
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: build dependencies
          command: |
            gem update --system
            gem install bundler
            gem install rake

      - run:
          name: build the jekyll site
          command:  bundle exec jekyll build

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
